### ISSUE TITLE
Missing lifecycle methods

### ISSUE THREAD

**Issue by arjunm8** [googleads/googleads-mobile-android-native-templates#13]
The templateView doesn't seem to have methods like .pause(), .resume(), etc like other standard adViews.

Is this something that's natively handled now because it used to be practice to call these in the overriden activity lifecycle methods to prevent displaying ads when not in foreground.

Sorry if this is a dumb Q.

**Comment by stowy** [comment]
Hi @arjunm8 - no worries happy to clarify. Unlike banner ads, native ad views don't have such methods.  Any such methods are on the native ads themselves.

If you consult [our documentation](https://developers.google.com/admob/android/native/start#loading_ads) you will find all the details around handling the ad lifecycle. Note that native ads do not have pause or resume methods but they do have a `destroy()` method.

**Comment by arjunnvn** [comment]
Ah makes sense, Thanks!
