### ISSUE TITLE
Can't import module android studio 4.2.1

### ISSUE THREAD

**Issue by michalguspiel** [googleads/googleads-mobile-android-native-templates#23]
Can't import module, after importing gradle won't sync, been trying to clean project, rebuild project, restart cache, restart android studio. After removing module from project everything works like supposed to.

**Comment by sardarvanshi** [comment]
i faced same problem

**Comment by emoboyfriend** [comment]
I am also too.

**Comment by Riyaz0001** [comment]
same problem here?

**Comment by kannasaikiran** [comment]
so guys i tried almost all the solutions none worked. 

What i did is i download the older version of the android studio android-studio-2020.3.1.3 and tried that . 
It worked A okey.

**Comment by prince02765** [comment]
I'm also getting the same error finish button is not clickable.

If someone find solution please let us know.

**Comment by EbisaKebede** [comment]
I'm also getting the same error

**Comment by yoonseopshin** [comment]
I also faced same error, but I solved it this way:
1. Copy `nativetemplates` folder & paste unter the project folder
2. Add `nativetemplates` module to `settings.gradle` file
```
rootProject.name = YOUR-PROJECT-NAME
include ':app'
include ':nativetemplates'
``` 
3. Rebuild project

**Comment by yoonseopshin** [comment]
I also faced same error, but I solved it this way:
1. Copy `nativetemplates` folder & paste unter the project folder
2. Add `nativetemplates` module to `settings.gradle` file
```
rootProject.name = YOUR-PROJECT-NAME
include ':app'
include ':nativetemplates'
``` 
3. Rebuild project

**Comment by yoonseopshin** [comment]
I also faced same error, but I solved it this way:
1. Copy `nativetemplates` folder & paste unter the project folder
2. Add `nativetemplates` module to `settings.gradle` file
```
rootProject.name = YOUR-PROJECT-NAME
include ':app'
include ':nativetemplates'
``` 
3. Rebuild project

**Comment by DawnImpulse** [comment]
@yoonseopshin working like a charm.. thx :)

**Comment by JillSong** [comment]
Issue addressed by https://github.com/googleads/googleads-mobile-android-native-templates/pull/39.
