### ISSUE TITLE
Jar file needed for Native template

### ISSUE THREAD

**Issue by jewelshkjony** [googleads/googleads-mobile-android-native-templates#27]
I need jar file for this library. I'm using Mit App Inventor 2 platform to build Android application. Mit not support .aar file. Also it's not support gradle dependency. There I can't inflate any view. That's why I need .jar file to show Admob native ad. Please build a jar for me. (Thanks for your valuable time)

**Comment by JillSong** [comment]
Hi @jewelshkjony I'm sorry it is not in our product roadmap to build for your specific chosen platform.

**Comment by jewelshkjony** [comment]
No problem, I'm using a trick here to show custom design Native ad here.
