### ISSUE TITLE
CanIgnoreReturnValue Error

### ISSUE THREAD

**Issue by DarkEye42** [googleads/googleads-mobile-android-native-templates#31]
In NativeTemplateStyle.java can not resolve symble
import com.google.errorprone.annotations.CanIgnoreReturnValue

" CanIgnoreReturnValue " can't find.

**Comment by NomanShaikh175** [comment]
did you find the solution? I am facing the same problem.

**Comment by HmimssaSoufiane** [comment]
Same i go back to old version .

**Comment by DarkEye42** [comment]
I didn't find any solutions so I left Admob and using Unity now. It's better than Admob. eCPM rate is also high.

**Comment by arafaatqureshi** [comment]
@DarkEye42 @NomanShaikh175 @HmimssaSoufiane 
Add this dependency in your nativetemplate module gradle file 
implementation 'com.google.errorprone:error_prone_annotations:2.9.0'

**Comment by lilcheti** [comment]
why not fixing this already?

**Comment by RakshakManchanda** [comment]
> @DarkEye42 @NomanShaikh175 @HmimssaSoufiane Add this dependency in your nativetemplate module gradle file implementation 'com.google.errorprone:error_prone_annotations:2.9.0'

Thanks for the Quick Solution. But it will just take a single commit to resolve this issue for new users. @maddevrelgithubbot  @kluever Please implement this thing so that the code should be error free for a newbie.
