### ISSUE TITLE
Getting namespace issue with nativetemplate

### ISSUE THREAD

**Issue by grvsingh44** [googleads/googleads-mobile-android-native-templates#42]
A problem occurred configuring project ':nativetemplates'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build

**Comment by NVentimiglia** [comment]
@grvsingh44 

I would love to help you with this issue, can you provide me your replication steps?

**Comment by JillSong** [comment]
@grvsingh44 Feel free to re-open the issue once you can provide us steps to reproduce the issue.
