### ISSUE TITLE
gradle file target sdk

### ISSUE THREAD

**Issue by pavanjoshi914** [googleads/googleads-mobile-android-native-templates#43]
i see this template uses compile sdk 30. it shall target to new android versions such as api level 34. keeping the same config will effect my app? my app targets from api level 21 to api level 34

**Comment by NVentimiglia** [comment]
@pavanjoshi914 

The compile sdk should not affect runtime behaviour, it is used at compile time by gradle. Yes, please upgrade to the latest compile api level as demanded by the google mobile ads sdk and all other dependencies.
